import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const font = Inter({
  weight: ["400","800", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Software Developer Portfolio, frontend developer, backend developer, fullstack developer - Olayenikan Michael Pounds",
  description: "Generated by olayenikan-michael pounds michaels digital consultancy portfolio ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased bg-blue-950`}
      >
        {children}
      </body>
    </html>
  );
}
