import type { Metadata } from "next";
import { Geist, Geist_Mono ,Outfit,Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "./Components/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"], weight:["200","400","600", "800"]
});

const font = Inter({
subsets: ["latin"], weight:["200","400","600", "800"]
});


const Outfitsan = Outfit({
subsets: ["latin"], weight:["200","400","600", "800"]
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Olayenikan-Michael Software Eng",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${font.className}  ${Outfitsan} antialiased`}
      >
        
   
        {/* <Navbar/> */}
        {children}
      </body>
    </html>
  );
}
